ALTER TABLE boop_sizes
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE chores
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE join_chore_tags
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE join_chore_task_types
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE join_task_types_tags
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE task_types
    ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks
    ENABLE ROW LEVEL SECURITY;